# Generated by Django 5.1.3 on 2024-12-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Friend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="pending", max_length=255)),
            ],
            options={
                "verbose_name_plural": "Friends",
                "db_table": "friends",
                "managed": False,
            },
        ),
    ]
