# Generated by Django 5.1.3 on 2024-12-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                (
                    "password",
                    models.CharField(
                        db_column="password_hash",
                        max_length=255,
                        verbose_name="password",
                    ),
                ),
                ("admin", models.BooleanField(default=False)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("dark_mode", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("show_friends", models.BooleanField(default=True)),
                ("public_profile", models.BooleanField(default=True)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                ("opt_out", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "users",
                "managed": True,
            },
        ),
    ]
