# Generated by Django 5.1.3 on 2024-12-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameCategories",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "game_categories",
                "ordering": ["category_name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GameCategoriesLink",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "game_categories_link",
                "ordering": ["category__category_name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GameGenres",
            fields=[
                ("genre_id", models.AutoField(primary_key=True, serialize=False)),
                ("genre_name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "game_genres",
                "ordering": ["genre_name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GameGenresLink",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "game_genres_link",
                "ordering": ["genre__genre_name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GamePlatforms",
            fields=[
                ("platform_id", models.AutoField(primary_key=True, serialize=False)),
                ("platform_name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "game_platforms",
                "ordering": ["platform_name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GamePlatformsLinks",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "game_platforms_link",
                "ordering": ["platform__platform_name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Games",
            fields=[
                ("appid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("release_date", models.DateField()),
                ("english", models.BooleanField()),
                ("developer", models.CharField(max_length=255)),
                ("publisher", models.CharField(max_length=255)),
                ("required_age", models.IntegerField()),
                ("achievements", models.IntegerField()),
                ("positive_ratings", models.IntegerField()),
                ("negative_ratings", models.IntegerField()),
                ("median_playtime", models.IntegerField()),
                ("average_playtime", models.IntegerField()),
                ("owners", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("description", models.TextField()),
                ("short_description", models.TextField()),
                ("steam_image", models.URLField(max_length=255)),
                ("tiny_image", models.URLField(max_length=255)),
            ],
            options={
                "db_table": "games",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GameSessions",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_timestamp", models.DateTimeField(auto_now_add=True)),
                ("end_timestamp", models.DateTimeField(null=True)),
                ("total_time", models.FloatField()),
                ("ongoing", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "game_sessions",
                "ordering": ["user_game", "start_timestamp"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GameSteamspyTags",
            fields=[
                ("tag_id", models.AutoField(primary_key=True, serialize=False)),
                ("tag_name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "game_steamspy_tags",
                "ordering": ["tag_name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GameSteamspyTagsLink",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "game_steamspy_tags_link",
                "ordering": ["tag__tag_name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserGames",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("last_played", models.DateField()),
                ("hours_played", models.IntegerField()),
            ],
            options={
                "db_table": "user_games",
                "ordering": ["user", "app"],
                "managed": False,
            },
        ),
    ]
